export const allTags = [
  "Activities for couples",
  "Architecture",
  "Bike",
  "Bridges",
  "Breweries, distilleries, & vineyards",
  "Bus / coach",
  "Car",
  "Children's activities",
  "City sightseeing",
  "Drinks",
  "Food",
  "Local culture",
  "Museums",
  "Outdoor",
  "Parks & gardens",
  "Photography",
  "Religious sites",
  "Restaurants & bars",
  "Rivers",
  "River boat",
  "Sailboat",
  "Shopping malls",
  "Sightseeing cruise",
  "Squares & plazas",
  "Stations",
  "Tasting",
  "Tuk tuk",
  "Van",
  "Water activities",
  "Wine tasting",
  "Yacht",
  "Jeep / SUV",
];


